# Generated by Django 2.1.5 on 2019-03-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
