# Generated by Django 2.1.5 on 2019-03-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190320_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='like_user_set',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
